# Generated by Django 3.2.7 on 2021-12-13 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('bonus', models.FloatField(default=0.0)),
                ('capital', models.FloatField(default=0.0)),
                ('asset', models.IntegerField(default=0)),
                ('profit', models.FloatField(default=0.0)),
                ('btc', models.FloatField(default=0.0)),
                ('usd', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.FloatField(default=0.0, primary_key=True, serialize=False)),
                ('tp', models.CharField(choices=[('Withdraw', 'WD'), ('Deposit', 'Dp')], max_length=15)),
            ],
        ),
    ]
